#!/usr/bin/env python

import argparse

import requests

parser = argparse.ArgumentParser(description='remove a batch from wjc, this deletes everything (including running stuff)!')

parser.add_argument('server', help='specify the web server address')
parser.add_argument('code', help='batch code you got from submit')


args = parser.parse_args()

args = args.__dict__

headers = {'User-agent': 'Luke/1.0'}
r = requests.delete('http://%s/wjc/batch/%s' % (args['server'], args['code']), headers=headers)
print 'your batch %s has been deleted (%s)' % (args['code'], r.content)
