#!/usr/bin/env python

import argparse
import json
import requests

parser = argparse.ArgumentParser(description='submit a job to the wjc, instance types can be found here: http://aws.amazon.com/ec2/instance-types/.')

parser.add_argument('server', help='specifiy the web server address')
parser.add_argument('ami', help='ami id')
parser.add_argument('instance_type', help='AWS instance type')
parser.add_argument('batch', help='maximum amount of nodes if batch (0 for non-batch)')


args = parser.parse_args()

args = args.__dict__

num = 0
if args['batch'] is not None:
    num = args['batch']
data = json.dumps({'ami': args['ami'], 'instance_type': args['instance_type']})
if num == 0:
    r = requests.post('http://%s/wjc/jobs' % args['server'], data=data)
else:
    r = requests.post('http://%s/wjc/batch/%s' % (args['server'], num), data=data)
print 'your job code is : %s' % r.content
